CREATE TABLE usuarios (
  USR_ID SERIAL PRIMARY KEY,
  USR_NOME VARCHAR(100) NOT NULL,
  USR_EMAIL VARCHAR(100) UNIQUE NOT NULL,
  USR_SENHA VARCHAR(255) NOT NULL,
  USR_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ativos (
  ATV_ID SERIAL PRIMARY KEY,
  USR_ID INTEGER REFERENCES usuarios(USR_ID),
  ATV_NOME VARCHAR(100) NOT NULL,
  ATV_DESCRICAO TEXT,
  ATV_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE manutencoes (
  MAN_ID SERIAL PRIMARY KEY,
  ATV_ID INTEGER REFERENCES ativos(ATV_ID) ON DELETE CASCADE,
  MAN_DES_SERVICO TEXT NOT NULL,
  MAN_DESCRICAO_DETALHADA TEXT,
  MAN_DATA_EXECUCAO DATE NOT NULL,
  MAN_PROXIMA_DATA DATE,
  MAN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

